pipeline:
  identifier: Build_AdityaJ1222_hello_world_app_1749632418751
  name: Build hello-world-app
  orgIdentifier: default
  projectIdentifier: helloworldtest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: AdityaJ1222/hello-world-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerrepoconnector
                    repo: adityaa12/harness-hello-world
                    tags:
                      - v1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
